### ISSUE TITLE
`lost-vars` not recognized

### ISSUE THREAD

**Issue by stephanschubert** [delorge/stylelint-config-lost#2]
[`lost-gutter` and `lost-gutter-local` are deprecated](http://lostgrid.org/docs.html#variables) according to the documentation and should be accessed via `lost-vars()`.

Using

```
  margin-bottom: calc(lost-vars('gutter') * 2);
```

`stylelint` complains about:

```
    29  25 error    funct… Expected single space before "-" operator (function-calc-no-unspaced-operator) (css-stylelint)
    29  25 error    funct… Expected single space after "-" operator (function-calc-no-unspaced-operator) (css-stylelint)
```

**Comment by delorge** [comment]
@jazen seems to be an issue with stylelint rule itself (dash is considered as subtraction sign)

upd: after expecting the [code]( https://github.com/stylelint/stylelint/blob/master/lib/rules/function-calc-no-unspaced-operator/index.js ) I'm not sure if stylelint team would consider rewriting rule for 3rd party custom functions. 

upd 2: could you pls create an issue in [lost repo](https://github.com/peterramsing/lost/issues/new) with your setup specified and link this issue as well? pls cc me there

upd3: also [this is why stylelint wasn't throwing anything before](https://github.com/stylelint/stylelint/blob/master/lib/rules/function-calc-no-unspaced-operator/index.js#L67)

**Comment by stephanschubert** [comment]
@delorge [Just did!](https://github.com/peterramsing/lost/issues/409)

**Comment by peterramsing** [comment]
Well, this is quite unfortunate. I'm a bit embarrassed that this didn't get caught before we implemented it. 🤔 I agree, there shouldn't be a need for stylelint to have to work around our mistake. I'll look into the next steps. Thanks for bringing this up.

**Comment by delorge** [comment]
ok, hope lost-grid guys will figure it out. I close this issue for now.
